<?php

namespace Proxies\__CG__\Sylius\Bundle\CoreBundle\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \Sylius\Bundle\CoreBundle\Model\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'user', 'shippingAddress', 'billingAddress', 'shipments', 'payment', 'currency', 'promotionCoupon', 'paymentState', 'shippingState', 'promotions', 'expiresAt', 'id', 'completedAt', 'number', 'items', 'itemsTotal', 'adjustments', 'adjustmentsTotal', 'total', 'confirmed', 'confirmationToken', 'createdAt', 'updatedAt', 'deletedAt', 'state');
        }

        return array('__isInitialized__', 'user', 'shippingAddress', 'billingAddress', 'shipments', 'payment', 'currency', 'promotionCoupon', 'paymentState', 'shippingState', 'promotions', 'expiresAt', 'id', 'completedAt', 'number', 'items', 'itemsTotal', 'adjustments', 'adjustmentsTotal', 'total', 'confirmed', 'confirmationToken', 'createdAt', 'updatedAt', 'deletedAt', 'state');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Sylius\Bundle\CoreBundle\Model\UserInterface $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', array());

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress(\Sylius\Bundle\AddressingBundle\Model\AddressInterface $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', array($address));

        return parent::setShippingAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\Sylius\Bundle\AddressingBundle\Model\AddressInterface $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($address));

        return parent::setBillingAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxTotal', array());

        return parent::getTaxTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAdjustments', array());

        return parent::getTaxAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function removeTaxAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTaxAdjustments', array());

        return parent::removeTaxAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionTotal', array());

        return parent::getPromotionTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionAdjustments', array());

        return parent::getPromotionAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function removePromotionAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromotionAdjustments', array());

        return parent::removePromotionAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTotal', array());

        return parent::getShippingTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAdjustments', array());

        return parent::getShippingAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function removeShippingAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShippingAdjustments', array());

        return parent::removeShippingAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayment', array());

        return parent::getPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayment(\Sylius\Bundle\PaymentsBundle\Model\PaymentInterface $payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayment', array($payment));

        return parent::setPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentState', array());

        return parent::getPaymentState();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentState($paymentState)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentState', array($paymentState));

        return parent::setPaymentState($paymentState);
    }

    /**
     * {@inheritDoc}
     */
    public function getInventoryUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventoryUnits', array());

        return parent::getInventoryUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function getInventoryUnitsByVariant(\Sylius\Bundle\CoreBundle\Model\VariantInterface $variant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventoryUnitsByVariant', array($variant));

        return parent::getInventoryUnitsByVariant($variant);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipments', array());

        return parent::getShipments();
    }

    /**
     * {@inheritDoc}
     */
    public function hasShipments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasShipments', array());

        return parent::hasShipments();
    }

    /**
     * {@inheritDoc}
     */
    public function addShipment(\Sylius\Bundle\CoreBundle\Model\ShipmentInterface $shipment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShipment', array($shipment));

        return parent::addShipment($shipment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShipment(\Sylius\Bundle\CoreBundle\Model\ShipmentInterface $shipment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShipment', array($shipment));

        return parent::removeShipment($shipment);
    }

    /**
     * {@inheritDoc}
     */
    public function hasShipment(\Sylius\Bundle\CoreBundle\Model\ShipmentInterface $shipment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasShipment', array($shipment));

        return parent::hasShipment($shipment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionCoupon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionCoupon', array());

        return parent::getPromotionCoupon();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionCoupon(\Sylius\Bundle\PromotionsBundle\Model\CouponInterface $coupon = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionCoupon', array($coupon));

        return parent::setPromotionCoupon($coupon);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionSubjectItemTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionSubjectItemTotal', array());

        return parent::getPromotionSubjectItemTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionSubjectItemCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionSubjectItemCount', array());

        return parent::getPromotionSubjectItemCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingState', array());

        return parent::getShippingState();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingState', array($state));

        return parent::setShippingState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function isBackorder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBackorder', array());

        return parent::isBackorder();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastShipment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastShipment', array());

        return parent::getLastShipment();
    }

    /**
     * {@inheritDoc}
     */
    public function isInvoiceAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInvoiceAvailable', array());

        return parent::isInvoiceAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function hasPromotion(\Sylius\Bundle\PromotionsBundle\Model\PromotionInterface $promotion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPromotion', array($promotion));

        return parent::hasPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function addPromotion(\Sylius\Bundle\PromotionsBundle\Model\PromotionInterface $promotion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPromotion', array($promotion));

        return parent::addPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function removePromotion(\Sylius\Bundle\PromotionsBundle\Model\PromotionInterface $promotion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromotion', array($promotion));

        return parent::removePromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotions', array());

        return parent::getPromotions();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', array());

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', array());

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiresAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiresAt', array());

        return parent::getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $expiresAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', array($expiresAt));

        return parent::setExpiresAt($expiresAt);
    }

    /**
     * {@inheritDoc}
     */
    public function incrementExpiresAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'incrementExpiresAt', array());

        return parent::incrementExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function isCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCompleted', array());

        return parent::isCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function complete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'complete', array());

        return parent::complete();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompletedAt', array());

        return parent::getCompletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompletedAt(\DateTime $completedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompletedAt', array($completedAt));

        return parent::setCompletedAt($completedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', array());

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setItems(\Doctrine\Common\Collections\Collection $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItems', array($items));

        return parent::setItems($items);
    }

    /**
     * {@inheritDoc}
     */
    public function clearItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearItems', array());

        return parent::clearItems();
    }

    /**
     * {@inheritDoc}
     */
    public function countItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countItems', array());

        return parent::countItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\Sylius\Bundle\OrderBundle\Model\OrderItemInterface $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', array($item));

        return parent::addItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\Sylius\Bundle\OrderBundle\Model\OrderItemInterface $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', array($item));

        return parent::removeItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function hasItem(\Sylius\Bundle\OrderBundle\Model\OrderItemInterface $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasItem', array($item));

        return parent::hasItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsTotal', array());

        return parent::getItemsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsTotal($itemsTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsTotal', array($itemsTotal));

        return parent::setItemsTotal($itemsTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function calculateItemsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateItemsTotal', array());

        return parent::calculateItemsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjustments', array());

        return parent::getAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdjustment(\Sylius\Bundle\OrderBundle\Model\AdjustmentInterface $adjustment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdjustment', array($adjustment));

        return parent::addAdjustment($adjustment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdjustment(\Sylius\Bundle\OrderBundle\Model\AdjustmentInterface $adjustment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdjustment', array($adjustment));

        return parent::removeAdjustment($adjustment);
    }

    /**
     * {@inheritDoc}
     */
    public function hasAdjustment(\Sylius\Bundle\OrderBundle\Model\AdjustmentInterface $adjustment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAdjustment', array($adjustment));

        return parent::hasAdjustment($adjustment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjustmentsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjustmentsTotal', array());

        return parent::getAdjustmentsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function clearAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearAdjustments', array());

        return parent::clearAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateAdjustmentsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateAdjustmentsTotal', array());

        return parent::calculateAdjustmentsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function calculateTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateTotal', array());

        return parent::calculateTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', array());

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt(\DateTime $deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalItems', array());

        return parent::getTotalItems();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalQuantity', array());

        return parent::getTotalQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function isEmpty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEmpty', array());

        return parent::isEmpty();
    }

}
